### ISSUE TITLE
File format errer ex01.ac7

### ISSUE THREAD

**Issue by pv-kob** [michgz/ac7maker#2]
Since I bought a CASIO CT-X5000 keyboard, I have been trying to write a program to convert AC7 rhythm files to mid and vice versa in Delphi, but so far to no avail.
Following all the instructions to AC7maker I created the ex01.ac7 file, but when I try to transfer the file to the keyboard using DataManagerCTX.exe, I get an error:
File format errer ex01.ac7
What can you advise me?
My e-mail is tp_kob@mail.ru
P.S I know the Delphi programming language and Python language a little

**Comment by michgz** [comment]
Hi pv-kob, thanks for the report. Could you please confirm the size of the ex01.ac7 file? It's expected 5067 bytes (approx. 4.9KB)

**Comment by pv-kob** [comment]
Hi michgz! 
I apologize, When I created a bat-file I just made a mistake and therefore I got an AC7 file of 0 bytes in size. Now everything is all right. I'm trying to figure out how the program works.
P.S There is another very interesting, but not finished development in Visual Basic for Eccel. I'm trying to remake her Delphi gender, but can't find a specification for AC7 and CKF formats. Can you help me with it?

**Comment by pv-kob** [comment]
CASIO RhythmConv v2.3 modified
Link: http://casio.medivm.ru/casio_rhythm_converter_doc.html

**Comment by shimpe** [comment]
If you are ok with GPLv3 license, you can take a look at my projects https://github.com/shimpe/ac7parser and https://github.com/shimpe/ac7renamer

The ac7parser understands the ac7 format fairly well (some details I could not reverse engineer since I don't have a recent casio keyboard model) and the ac7renamer does some manipulations to ac7 files, like reordering variations, changing the displayed style name and unlocking tracks for editing. If you are using windows, you can download a premade executable from the casio music forum thread: https://www.casiomusicforums.com/index.php?/topic/17296-ac7-style-file-renamer-testers-wanted (use the most recent links near the end of the discussion on page 7 or so).

I was considering to add something to convert midi -> ac7 or vice versa in the future, but at the same time I don't want to reinvent the wheel, so if ac7maker already does it well, then there's no need for me to dive in.

**Comment by michgz** [comment]
Hi pv-kob,
That's good I will close this issue as done. Feel free to open others if needed.

As far as I know there is no official documentation for AC7. I was started off by Shimpe's work (as linked above) plus additional experimentation. I think that is as close to documentation as exists.

By complete coincidence I came across the RhythmConv just yesterday evening. I haven't been able to run it yet. When you say it is not finished, what do you mean? What is not finished about it? (Just asking so as to not waste time if it doesn't work)

**Comment by pv-kob** [comment]
RhythmConv is partially functional. It normally converts SMF (mid) files to .ckf and .fs7 files (the keyboard plays them quite well) but it gives errors when trying to load AC7 files from CT-X3000-5000 keyboards. In particular, the program does not recognize some atoms in the ELMT section, such as 0x9, 0x11, 0x40, 0x41, 0x42, 0x45, 0x 46, 0x47 and 0x48. And that's not all that I was able to analyze. If you are interested, I am sending  'raw' source in Delphi 7.
[CASIO Rhythm Converter (Delphi).zip](https://github.com/michgz/ac7maker/files/5993437/CASIO.Rhythm.Converter.Delphi.zip)

**Comment by michgz** [comment]
Is your Delphi program able to transform Yamaha .STY files into .AC7? That is something some users at casiomusicforums.com have been asking, and also from above it seems Shimpe is also thinking about this type of program.

I think my ac7maker is not suitable because the MIDI input is in a different form (it doesn't use Marker events to separate tracks), and even if that was changed there needs to be a GUI for adjusting assignments of instruments. As long as your program runs, it would be useful to people if you release it now.

**Comment by michgz** [comment]
By the way, the meaning of the 0x11 atom is documented at ac7maker.py lines 617-636. Hope that's useful

**Comment by pv-kob** [comment]
I was thinking about something else, could someone write a program for playing AC7 files, like the already existing program clf-player (in the attached file). It would be great in general.
[CkfRhythmPlayerv21.zip](https://github.com/michgz/ac7maker/files/6000397/CkfRhythmPlayerv21.zip)

**Comment by pv-kob** [comment]
I don't know about converting Yamaha .STY rhythms, because I just took the source code of CASIO_RhythmConv v2.3 modified, written in Visual Basic as a macro for Eccel and tried to adapt this code for Delphi (not complete implemenyed yet), since this language is more understandable for me, and besides, it is easier to organize a graphical interface on it.
[CASIO_RhythmConv v2.3.zip](https://github.com/michgz/ac7maker/files/6000429/CASIO_RhythmConv.v2.3.zip)

**Comment by michgz** [comment]
pv-kob, let's continue this conversation by e-mail.

**Comment by pv-kob** [comment]
Ok. I agre
